#!/bin/bash
if [ -e ~/.menu/$1.menu ]; then
	cmd=`~/.menu/$1.menu $2 | dmenu -i`
elif [ -e ~/.menu/$1.sqlite ]; then
	cmd=`sqlite3 -line ~/.menu/$1.sqlite "SELECT name FROM commands ORDER BY weight DESC" | grep -v "^$" | cut -b 9- | dmenu -i`
else
	echo "menu file not found"
	exit
fi

if [[ "$cmd" == *\; ]]; then
	prefix="urxvt -e "
	cmd="${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	prefix="gksu "
	cmd="${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	prefix="m "
	cmd="${cmd%?}"
fi

if [ -e ~/.menu/$1.post ]; then
	cmd=`echo $cmd | ~/.menu/$1.post $2`
fi

if [[ "$cmd" == *\; ]]; then
	prefix="urxvt -e "
	cmd="${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	prefix="gksu "
	cmd="${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	prefix="m "
	cmd="${cmd%?}"
fi

$SHELL -c "$prefix$cmd"
