#!/bin/bash
if [ -e ~/.menu/$1.menu ]; then
	cmd=`~/.menu/$1.menu $2 | dmenu -i`
elif [ -e ~/.menu/$1.sqlite ]; then
	cmd=`sqlite3 -line ~/.menu/$1.sqlite "SELECT name FROM commands ORDER BY weight DESC" | grep -v "^$" | cut -b 9- | dmenu -i`
else
	echo "menu file not found"
	exit
fi

if [ -e ~/.menu/$1.post ]; then
	cmd=`echo $cmd | ~/.menu/$1.post $2`
fi

if [[ "$cmd" == *\; ]]; then
	cmd="urxvt -e ${cmd%\;}"
elif [[ "$cmd" == *\! ]]; then
	cmd="gksu ${cmd%!}"
elif [[ "$cmd" == *\? ]]; then
	cmd="m ${cmd%?}"
fi

$cmd
